### PR TITLE
Fetch multiple pages of image tags

### PR DESCRIPTION
**Pull request by TylerLubeck**
This utilizes Unirest's pagination fetcher to allow for fetching tags from multiple pages of results.

From what I can tell, the docker hub uses very long pages while Amazon's ECR uses 100 item pages.

The registry v2 API exposes pagination for images:
https://docs.docker.com/registry/spec/api/#pagination-1

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

I've installed and tested this on my local Jenkins instances against both ECR and primary docker hub. I'm not sure how to test it beyond that, but I'm happy to do so if someone can give me some pointers?

### CODE REVIEW

**Review by h1dden-da3m0n — APPROVED** [review]

**Comment by esevland-chwy** [comment]
Anything we can do to help get this PR through? It would be really nice to have this added. Thanks.

**Comment by TylerLubeck** [comment]
I fixed up the merge conflicts, but I'm no longer working with Jenkins so I'm not sure how much I can do to shepherd this through.

**Comment by kolivero-chwy** [comment]
how can we get this PR review it and planned for a near future?

**Comment by ragnor** [comment]
Any progress on this? I'd like to use the plugin but due to the issue the content of the list is incomplete.

**Comment by sebastianhutter** [comment]
I would need the pagination in place too. Any progress on the PR?

**Comment by siriak** [comment]
Bump. Any updates?

**Review by siriak — APPROVED** [review]

**Comment by ragumix** [comment]
any news?

**Comment by TylerLubeck** [comment]
I'm going to close this. I no longer use Jenkins and have no way of testing this any further. If anyone else would like to take this on, I believe the only remaining steps here are to get it reviewed by someone with merge access to the repo, then merge and ship.

**Pull request closed without merging**
